import asyncio
import argparse
import uvicorn
from fastapi import FastAPI
import httpx
from pydantic import BaseModel

app = FastAPI(title="Mock GPU Worker")

class RequestModel(BaseModel):
    query: str

class ResponseModel(BaseModel):
    response: str

# Worker metadata
WORKER_ID = "mock-cpu-node-1"
WORKER_PORT = 8001
WORKER_HOST = "localhost"
GPU_NAME = "Simulated CPU Node"

@app.get("/health")
def health():
    return {"status": "ok"}

@app.post("/process", response_model=ResponseModel)
async def process(req: RequestModel):
    # Simulate processing delay
    await asyncio.sleep(0.5)
    return ResponseModel(response=f"[Generated by {WORKER_ID}] This is a mocked answer for: {req.query}")

async def register_with_scheduler():
    scheduler_url = "http://localhost:9000/register"
    payload = {
        "worker_id": WORKER_ID,
        "host": WORKER_HOST,
        "port": WORKER_PORT,
        "gpu_name": GPU_NAME
    }
    
    # Try registering until successful
    while True:
        try:
            async with httpx.AsyncClient() as client:
                resp = await client.post(scheduler_url, json=payload, timeout=3.0)
                if resp.status_code == 200:
                    print(f"✅ Successfully registered {WORKER_ID} with the Scheduler!")
                    break
                else:
                    print(f"⚠️ Failed to register: HTTP {resp.status_code}")
        except Exception as e:
            print(f"⏳ Scheduler not reachable, retrying in 3 seconds... ({e})")
        await asyncio.sleep(3)

@app.on_event("startup")
async def startup_event():
    asyncio.create_task(register_with_scheduler())

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8001)
    parser.add_argument("--worker-id", type=str, default="mock-cpu-node-1")
    args = parser.parse_args()
    
    WORKER_PORT = args.port
    WORKER_ID = args.worker_id
    
    uvicorn.run(app, host="0.0.0.0", port=WORKER_PORT)
